const transportTypes = [
  { id: 1, name: 'Minibus' },
  { id: 2, name: 'Bus' },
  { id: 3, name: 'Taxi' },
  { id: 4, name: 'Other' },
];

const routes = [
  { id: 1, name: 'Bole to Piazza', origin: 'Bole', destination: 'Piazza', description: 'DEMO DATA: sample route only.' },
  { id: 2, name: 'Megenagna to Saris', origin: 'Megenagna', destination: 'Saris', description: 'DEMO DATA: sample route only.' },
  { id: 3, name: 'Meskel Square to Mexico', origin: 'Meskel Square', destination: 'Mexico', description: 'DEMO DATA: sample route only.' },
  { id: 4, name: 'Kebena to Bole', origin: 'Kebena', destination: 'Bole', description: 'DEMO DATA: sample route only.' },
  { id: 5, name: 'Woreda 8 to Piassa', origin: 'Woreda 8', destination: 'Piassa', description: 'DEMO DATA: sample route only.' },
];

const stations = [
  {
    id: 1,
    name: 'Bole Lemi Transport Hub',
    description: 'DEMO DATA: sample station for UI testing and local development. Replace with verified station data later.',
    latitude: 8.9953,
    longitude: 38.7995,
    address: 'Bole Lemi, Addis Ababa',
    transport_type_ids: [1, 2],
    route_ids: [1, 4],
    destinations: ['Piazza', 'Bole', 'Megenagna'],
    operating_hours: '05:30 - 20:30',
  },
  {
    id: 2,
    name: 'Megenagna Station',
    description: 'DEMO DATA: sample station for UI testing and local development. Replace with verified station data later.',
    latitude: 9.0274,
    longitude: 38.7952,
    address: 'Megenagna, Addis Ababa',
    transport_type_ids: [1, 3],
    route_ids: [2, 4],
    destinations: ['Saris', 'Bole', 'Piazza'],
    operating_hours: '05:00 - 21:00',
  },
  {
    id: 3,
    name: 'Mexico Roundabout',
    description: 'DEMO DATA: sample station for UI testing and local development. Replace with verified station data later.',
    latitude: 9.0189,
    longitude: 38.7608,
    address: 'Mexico, Addis Ababa',
    transport_type_ids: [1, 2, 3],
    route_ids: [3, 5],
    destinations: ['Meskel Square', 'Piassa', 'Saris'],
    operating_hours: '24 Hours',
  },
  {
    id: 4,
    name: 'Meskel Square',
    description: 'DEMO DATA: sample station for UI testing and local development. Replace with verified station data later.',
    latitude: 9.0105,
    longitude: 38.7624,
    address: 'Meskel Square, Addis Ababa',
    transport_type_ids: [2, 3],
    route_ids: [3],
    destinations: ['Mexico', 'Bole', 'Piazza'],
    operating_hours: '05:00 - 20:00',
  },
  {
    id: 5,
    name: 'Saris Transport Stop',
    description: 'DEMO DATA: sample station for UI testing and local development. Replace with verified station data later.',
    latitude: 8.9802,
    longitude: 38.7911,
    address: 'Saris, Addis Ababa',
    transport_type_ids: [1, 4],
    route_ids: [2],
    destinations: ['Megenagna', 'Saris', 'Piazza'],
    operating_hours: '06:00 - 19:00',
  },
  {
    id: 6,
    name: 'Piassa Central Station',
    description: 'DEMO DATA: sample station for UI testing and local development. Replace with verified station data later.',
    latitude: 9.0337,
    longitude: 38.7562,
    address: 'Piassa, Addis Ababa',
    transport_type_ids: [1, 2, 3],
    route_ids: [1, 5],
    destinations: ['Bole', 'Megenagna', 'Kebena'],
    operating_hours: '05:00 - 21:30',
  },
];

module.exports = {
  transportTypes,
  routes,
  stations,
};
